version: '3.8'
services:
    server:
        image: 'docker.pkg.github.com/evotm/docker-trackmania/trackmania:latest'
        environment:
            MASTER_LOGIN: '${MASTER_LOGIN}'
            MASTER_PASSWORD: '${MASTER_PASSWORD}'
            SERVER_NAME: '${SERVER_NAME}'
            SYSTEM_XMLRPC_REMOTE: 'True'
            SYSTEM_DISABLE_REPLAYS: 'False'
            SYSTEM_SAVE_RUNS: 'False'
        healthcheck:
            test: 'nc -z -v 127.0.0.1 5000 || exit 1'
            interval: 5s
            timeout: 5s
            retries: 3
            start_period: 10s
        restart: always
        ports:
            - '10000-11000:2350/udp'
            - '10000-11000:2350/tcp'
        volumes:
            - 'serverData:/server/UserData'
            - '/var/run/docker.sock:/var/run/docker.sock:ro'
    evosc:
        image: 'docker.pkg.github.com/evotm/docker-evosc/evosc:latest'
        depends_on:
            server:
                condition: service_healthy
        healthcheck:
            test: 'pgrep -x php || exit 1'
            interval: 5s
            timeout: 5s
            retries: 3
            start_period: 10s
        restart: always
        environment:
            MASTER_LOGIN: '${MASTER_LOGIN}'
            DB_HOST: '10.0.0.10'
            DB_NAME: '${DB_NAME}'
            DB_USER: '${DB_USER}'
            DB_PASSWORD: '${DB_PASSWORD}'
            RPC_IP: 'server'
            RPC_LOGIN: 'SuperAdmin'
            RPC_PASSWORD: 'SuperAdmin'
        volumes:
            - 'serverData:/server/UserData'
            - 'evoscConfig:/controller/config'
            - 'evoscModules:/controller/modules'
            - 'evoscCache:/controller/cache'
volumes:
    serverData: null
    evoscConfig: null
    evoscModules: null
    evoscCache: null
