version: '3.8'
services:
    server:
        image: '${TRACKMANIA_IMAGE}'
        environment:
            MASTER_LOGIN: '${MASTER_LOGIN}'
            MASTER_PASSWORD: '${MASTER_PASSWORD}'
            SERVER_NAME: '${SERVER_NAME}'
            SERVER_PASSWORD: '${SERVER_PASSWORD}'
            SYSTEM_XMLRPC_REMOTE: '${SYSTEM_XMLRPC_REMOTE}'
            SYSTEM_DISABLE_REPLAYS: '${SYSTEM_DISABLE_REPLAYS}'
            SYSTEM_SAVE_RUNS: '${SYSTEM_SAVE_RUNS}'
        healthcheck:
            test: 'nc -z -v 127.0.0.1 5000 || exit 1'
            interval: 5s
            timeout: 5s
            retries: 3
            start_period: 10s
        restart: always
        ports:
            - '${PORT}:2350/udp'
            - '${PORT}:2350/tcp'
        volumes:
            - 'serverData:/server/UserData'
    evosc:
        image: '${CONTROLLER_IMAGE}'
        depends_on:
            server:
                condition: service_healthy
        healthcheck:
            test: 'pgrep -x php || exit 1'
            interval: 5s
            timeout: 5s
            retries: 3
            start_period: 10s
        restart: always
        environment:
            MASTER_LOGIN: '${MASTER_LOGIN}'
            DB_HOST: '${DB_HOST}'
            DB_NAME: '${DB_NAME}'
            DB_USER: '${DB_USER}'
            DB_PASSWORD: '${DB_PASSWORD}'
            RPC_IP: '${RPC_IP}'
            RPC_LOGIN: '${RPC_LOGIN}'
            RPC_PASSWORD: '${RPC_PASSWORD}'
        volumes:
            - 'serverData:/server/UserData'
            - 'evoscConfig:/controller/config'
            - 'evoscModules:/controller/modules'
            - 'evoscCache:/controller/cache'
volumes:
    serverData: null
    evoscConfig: null
    evoscModules: null
    evoscCache: null